"""Email automation module for CREA-RS validation requests."""
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from .data_models import InstitutionData, SolicitationData

EMAIL_SUBJECT_TEMPLATE = (
    "URGENTE: Solicitação de Confirmação de Dados para Registro Profissional "
    "CREA-RS (Ref: {cpf})"
)


def _build_email_body(solicitant_data: SolicitationData, institution_data: InstitutionData) -> str:
    """Build the validated email body using the enhanced template."""

    return f"""
Prezada(o) {institution_data.nome},

O Conselho Regional de Engenharia e Agronomia do Rio Grande do Sul (CREA-RS) está
conduzindo o processo de registro profissional do(a) solicitante abaixo, que apresentou
um diploma/certificado emitido por Vossa Instituição.

Para dar prosseguimento ao registro de atribuições técnicas, solicitamos urgentemente a
confirmação da veracidade e dos dados de conclusão do curso.

DADOS DO SOLICITANTE PARA VALIDAÇÃO:

* Nome Completo: {solicitant_data.nome_completo}
* CPF: {solicitant_data.cpf}
* Matrícula: {solicitant_data.matricula}
* Curso/Habilitação: {solicitant_data.curso}
* Carga Horária Total: {solicitant_data.carga_horaria}
* Período de Conclusão: {solicitant_data.periodo_conclusao}
* Data da Colação de Grau/Emissão: {solicitant_data.data_colacao}

A confirmação por e-mail, de forma clara e objetiva, é suficiente para a validação no nosso
sistema.

Solicitamos, preferencialmente, o envio do Número de Registro ou Código de Validação Digital
do diploma, se disponível.

Certos de sua colaboração para a rápida inserção de novos profissionais no mercado,
agradecemos a atenção.

Atenciosamente,

Núcleo de Habilitação e Registro Profissional
Conselho Regional de Engenharia e Agronomia do Rio Grande do Sul (CREA-RS)
Endereço Sede: [Rua e Número, Bairro]
Cidade/UF: Porto Alegre/RS
Telefone: [Telefone do CREA-RS]
"""


def send_validation_email(
    solicitant_data: SolicitationData,
    institution_data: InstitutionData,
    *,
    custom_sender: Optional[str] = None,
) -> str:
    """Send a validation email to the institution contact.

    Environment variables used for SMTP configuration:
    - CREA_SMTP_HOST
    - CREA_SMTP_PORT
    - CREA_SMTP_USER
    - CREA_SMTP_PASSWORD
    - CREA_SMTP_SENDER (optional override for the From header)

    Args:
        solicitant_data: Data about the professional solicitation.
        institution_data: Contact data for the issuing institution.
        custom_sender: Optional sender email to override environment default.

    Returns:
        The message ID string as generated by the SMTP server (if available).
    """

    smtp_host = os.environ.get("CREA_SMTP_HOST")
    smtp_port_raw = os.environ.get("CREA_SMTP_PORT", "587")
    smtp_user = os.environ.get("CREA_SMTP_USER")
    smtp_password = os.environ.get("CREA_SMTP_PASSWORD")
    sender = custom_sender or os.environ.get("CREA_SMTP_SENDER") or smtp_user

    if not smtp_host or not smtp_user or not smtp_password:
        raise ValueError("SMTP credentials are not fully configured in environment variables.")

    try:
        smtp_port = int(smtp_port_raw)
    except ValueError as exc:  # noqa: TRY003 - narrow error context is acceptable
        raise ValueError("CREA_SMTP_PORT must be an integer.") from exc

    subject = EMAIL_SUBJECT_TEMPLATE.format(cpf=solicitant_data.cpf)
    body = _build_email_body(solicitant_data, institution_data)

    message = MIMEMultipart()
    message["From"] = sender
    message["To"] = institution_data.email_contato
    message["Subject"] = subject
    message.attach(MIMEText(body, "plain", "utf-8"))

    with smtplib.SMTP(smtp_host, smtp_port) as smtp:
        smtp.starttls()
        smtp.login(smtp_user, smtp_password)
        response = smtp.send_message(message)

    return str(response)
